[2025-03-15T19:38:36.250+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [queued]>
[2025-03-15T19:38:36.271+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [queued]>
[2025-03-15T19:38:36.272+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-03-15T19:38:36.305+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_date> on 2025-03-12 22:00:00+00:00
[2025-03-15T19:38:36.318+0000] {standard_task_runner.py:60} INFO - Started process 2041 to run task
[2025-03-15T19:38:36.322+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'get_date', 'scheduled__2025-03-12T22:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpyijulqio']
[2025-03-15T19:38:36.324+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask get_date
[2025-03-15T19:38:36.437+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [running]> on host 42e0710fef4e
[2025-03-15T19:38:36.567+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='get_date' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T22:00:00+00:00'
[2025-03-15T19:38:36.569+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-03-15T19:38:36.570+0000] {python.py:201} INFO - Done. Returned value was: 2025-03-13
[2025-03-15T19:38:36.609+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=get_date, execution_date=20250312T220000, start_date=20250315T193836, end_date=20250315T193836
[2025-03-15T19:38:36.668+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-15T19:38:36.706+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T17:47:36.776+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [queued]>
[2025-03-17T17:47:36.800+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [queued]>
[2025-03-17T17:47:36.801+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-03-17T17:47:36.818+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_date> on 2025-03-12 22:00:00+00:00
[2025-03-17T17:47:36.827+0000] {standard_task_runner.py:60} INFO - Started process 528 to run task
[2025-03-17T17:47:36.832+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'get_date', 'scheduled__2025-03-12T22:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpc79ss0pg']
[2025-03-17T17:47:36.833+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask get_date
[2025-03-17T17:47:36.926+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.get_date scheduled__2025-03-12T22:00:00+00:00 [running]> on host d107d9d70093
[2025-03-17T17:47:37.076+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='get_date' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T22:00:00+00:00'
[2025-03-17T17:47:37.078+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-03-17T17:47:37.078+0000] {python.py:201} INFO - Done. Returned value was: 2025-03-13
[2025-03-17T17:47:37.113+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=get_date, execution_date=20250312T220000, start_date=20250317T174736, end_date=20250317T174737
[2025-03-17T17:47:37.178+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-17T17:47:37.221+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
