[2025-03-15T19:38:34.685+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-03-15T19:38:34.703+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-03-15T19:38:34.703+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-03-15T19:38:34.754+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_date> on 2025-03-11 22:00:00+00:00
[2025-03-15T19:38:34.767+0000] {standard_task_runner.py:60} INFO - Started process 2039 to run task
[2025-03-15T19:38:34.777+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'get_date', 'scheduled__2025-03-11T22:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp9726b5vm']
[2025-03-15T19:38:34.779+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask get_date
[2025-03-15T19:38:34.860+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [running]> on host 42e0710fef4e
[2025-03-15T19:38:35.030+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='get_date' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T22:00:00+00:00'
[2025-03-15T19:38:35.064+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-03-15T19:38:35.064+0000] {python.py:201} INFO - Done. Returned value was: 2025-03-12
[2025-03-15T19:38:35.118+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=get_date, execution_date=20250311T220000, start_date=20250315T193834, end_date=20250315T193835
[2025-03-15T19:38:35.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-15T19:38:35.268+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T17:47:35.250+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-03-17T17:47:35.268+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [queued]>
[2025-03-17T17:47:35.269+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-03-17T17:47:35.284+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_date> on 2025-03-11 22:00:00+00:00
[2025-03-17T17:47:35.292+0000] {standard_task_runner.py:60} INFO - Started process 526 to run task
[2025-03-17T17:47:35.295+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'get_date', 'scheduled__2025-03-11T22:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp3l9ukjo8']
[2025-03-17T17:47:35.299+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask get_date
[2025-03-17T17:47:35.395+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.get_date scheduled__2025-03-11T22:00:00+00:00 [running]> on host d107d9d70093
[2025-03-17T17:47:35.542+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='get_date' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T22:00:00+00:00'
[2025-03-17T17:47:35.544+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-03-17T17:47:35.545+0000] {python.py:201} INFO - Done. Returned value was: 2025-03-12
[2025-03-17T17:47:35.587+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=get_date, execution_date=20250311T220000, start_date=20250317T174735, end_date=20250317T174735
[2025-03-17T17:47:35.649+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-17T17:47:35.677+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
